image: node:12.12.0

stages:
  - build-dependencies
  - build
  - test
  - deploy

install_dependencies:
  stage: build-dependencies
  script:
    - npm install
      
cache:
  paths:
    - node_modules/
  
build-image:
  image: docker:19.03.1
  stage: build
  variables:
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ''
  services:
    - docker:19.03.1-dind
  script:
    - docker build -t api-reaction:1.0.0 .
  artifacts:
    paths:
      - dockerfile

jest:
  stage: test
  script:
    - npm run test

eslint:
  stage: test
  script:
    - npm run eslint

deploy:
  stage: deploy
  only: 
    - master
  script:
    - echo "deploy done"
